name: BETA Release
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

env:
  MS_URL: "https://marketplace.visualstudio.com/items?itemName=eliostruyf.send-to-copilot-cli"
  VSX_URL: "https://open-vsx.org/extension/eliostruyf/send-to-copilot-cli"

jobs:
  release-ms:
    name: "Release to VSCode Marketplace"
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '#release')
    environment:
      name: "Microsoft Marketplace"
      url: ${{ env.MS_URL }}

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Publish
        if: contains(github.event.head_commit.message, '#release')
        run: npx @vscode/vsce publish -p ${{ secrets.VSCE_PAT }}

  release-vsx:
    name: "Release to Open VSX"
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '#release')

    environment:
      name: "Open VSX"
      url: ${{ env.VSX_URL }}

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Publish to open-vsx.org
        if: contains(github.event.head_commit.message, '#release')
        run: npx ovsx publish -p ${{ secrets.OPEN_VSX_PAT }}
